package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.XXHR_REMOTE_WORK_EOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 07 15:28:40 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXHR_REMOTE_WORK_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXHR_REMOTE_WORK_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovalStatus,
        ApproverComments,
        BusinessUnitName,
        Cadre,
        Comments,
        Countries,
        CreatedBy,
        CreationDate,
        DeleteFlag,
        DepartmentName,
        DisclaimerFlag,
        Email,
        EndDate,
        ErrorMsg,
        FullName,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        Location,
        NoOfDays,
        PayrollBatchName,
        PersonId,
        PersonNumber,
        RemoteReqId,
        RemoteReqNo,
        RequestDate,
        SoaFlowid,
        StartDate,
        Title,
        RequestType,
        XxfndAttachment_EOView1,
        XxfndLookupValues_V_ROVO1,
        XXFND_TERRITORIES_ROVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int BUSINESSUNITNAME = AttributesEnum.BusinessUnitName.index();
    public static final int CADRE = AttributesEnum.Cadre.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int COUNTRIES = AttributesEnum.Countries.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DELETEFLAG = AttributesEnum.DeleteFlag.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int DISCLAIMERFLAG = AttributesEnum.DisclaimerFlag.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int FULLNAME = AttributesEnum.FullName.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LOCATION = AttributesEnum.Location.index();
    public static final int NOOFDAYS = AttributesEnum.NoOfDays.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int PERSONNUMBER = AttributesEnum.PersonNumber.index();
    public static final int REMOTEREQID = AttributesEnum.RemoteReqId.index();
    public static final int REMOTEREQNO = AttributesEnum.RemoteReqNo.index();
    public static final int REQUESTDATE = AttributesEnum.RequestDate.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int REQUESTTYPE = AttributesEnum.RequestType.index();
    public static final int XXFNDATTACHMENT_EOVIEW1 = AttributesEnum.XxfndAttachment_EOView1.index();
    public static final int XXFNDLOOKUPVALUES_V_ROVO1 = AttributesEnum.XxfndLookupValues_V_ROVO1.index();
    public static final int XXFND_TERRITORIES_ROVO1 = AttributesEnum.XXFND_TERRITORIES_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XXHR_REMOTE_WORK_VORowImpl() {
    }

    /**
     * Gets XXHR_REMOTE_WORK_EO entity object.
     * @return the XXHR_REMOTE_WORK_EO
     */
    public XXHR_REMOTE_WORK_EOImpl getXXHR_REMOTE_WORK_EO() {
        return (XXHR_REMOTE_WORK_EOImpl) getEntity(ENTITY_XXHR_REMOTE_WORK_EO);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @return the APPROVER_COMMENTS
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @param value value to set the APPROVER_COMMENTS
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_NAME using the alias name BusinessUnitName.
     * @return the BUSINESS_UNIT_NAME
     */
    public String getBusinessUnitName() {
        return (String) getAttributeInternal(BUSINESSUNITNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_NAME using the alias name BusinessUnitName.
     * @param value value to set the BUSINESS_UNIT_NAME
     */
    public void setBusinessUnitName(String value) {
        setAttributeInternal(BUSINESSUNITNAME, value);
    }

    /**
     * Gets the attribute value for CADRE using the alias name Cadre.
     * @return the CADRE
     */
    public String getCadre() {
        return (String) getAttributeInternal(CADRE);
    }

    /**
     * Sets <code>value</code> as attribute value for CADRE using the alias name Cadre.
     * @param value value to set the CADRE
     */
    public void setCadre(String value) {
        setAttributeInternal(CADRE, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for COUNTRIES using the alias name Countries.
     * @return the COUNTRIES
     */
    public String getCountries() {
        return (String) getAttributeInternal(COUNTRIES);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRIES using the alias name Countries.
     * @param value value to set the COUNTRIES
     */
    public void setCountries(String value) {
        setAttributeInternal(COUNTRIES, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for DELETE_FLAG using the alias name DeleteFlag.
     * @return the DELETE_FLAG
     */
    public String getDeleteFlag() {
        return (String) getAttributeInternal(DELETEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for DELETE_FLAG using the alias name DeleteFlag.
     * @param value value to set the DELETE_FLAG
     */
    public void setDeleteFlag(String value) {
        setAttributeInternal(DELETEFLAG, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @return the DEPARTMENT_NAME
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @param value value to set the DEPARTMENT_NAME
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for DISCLAIMER_FLAG using the alias name DisclaimerFlag.
     * @return the DISCLAIMER_FLAG
     */
    public String getDisclaimerFlag() {
        return (String) getAttributeInternal(DISCLAIMERFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCLAIMER_FLAG using the alias name DisclaimerFlag.
     * @param value value to set the DISCLAIMER_FLAG
     */
    public void setDisclaimerFlag(String value) {
        setAttributeInternal(DISCLAIMERFLAG, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Timestamp value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for FULL_NAME using the alias name FullName.
     * @return the FULL_NAME
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FULL_NAME using the alias name FullName.
     * @param value value to set the FULL_NAME
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LOCATION using the alias name Location.
     * @return the LOCATION
     */
    public String getLocation() {
        return (String) getAttributeInternal(LOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION using the alias name Location.
     * @param value value to set the LOCATION
     */
    public void setLocation(String value) {
        setAttributeInternal(LOCATION, value);
    }

    /**
     * Gets the attribute value for NO_OF_DAYS using the alias name NoOfDays.
     * @return the NO_OF_DAYS
     */
    public BigDecimal getNoOfDays() {
        return (BigDecimal) getAttributeInternal(NOOFDAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_OF_DAYS using the alias name NoOfDays.
     * @param value value to set the NO_OF_DAYS
     */
    public void setNoOfDays(BigDecimal value) {
        setAttributeInternal(NOOFDAYS, value);
    }

    /**
     * Gets the attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @return the PAYROLL_BATCH_NAME
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @param value value to set the PAYROLL_BATCH_NAME
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @return the PERSON_NUMBER
     */
    public BigDecimal getPersonNumber() {
        return (BigDecimal) getAttributeInternal(PERSONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_NUMBER using the alias name PersonNumber.
     * @param value value to set the PERSON_NUMBER
     */
    public void setPersonNumber(BigDecimal value) {
        setAttributeInternal(PERSONNUMBER, value);
    }

    /**
     * Gets the attribute value for REMOTE_REQ_ID using the alias name RemoteReqId.
     * @return the REMOTE_REQ_ID
     */
    public BigDecimal getRemoteReqId() {
        return (BigDecimal) getAttributeInternal(REMOTEREQID);
    }

    /**
     * Sets <code>value</code> as attribute value for REMOTE_REQ_ID using the alias name RemoteReqId.
     * @param value value to set the REMOTE_REQ_ID
     */
    public void setRemoteReqId(BigDecimal value) {
        setAttributeInternal(REMOTEREQID, value);
    }

    /**
     * Gets the attribute value for REMOTE_REQ_NO using the alias name RemoteReqNo.
     * @return the REMOTE_REQ_NO
     */
    public BigDecimal getRemoteReqNo() {
        return (BigDecimal) getAttributeInternal(REMOTEREQNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REMOTE_REQ_NO using the alias name RemoteReqNo.
     * @param value value to set the REMOTE_REQ_NO
     */
    public void setRemoteReqNo(BigDecimal value) {
        setAttributeInternal(REMOTEREQNO, value);
    }

    /**
     * Gets the attribute value for REQUEST_DATE using the alias name RequestDate.
     * @return the REQUEST_DATE
     */
    public Timestamp getRequestDate() {
        return (Timestamp) getAttributeInternal(REQUESTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_DATE using the alias name RequestDate.
     * @param value value to set the REQUEST_DATE
     */
    public void setRequestDate(Timestamp value) {
        setAttributeInternal(REQUESTDATE, value);
    }

    /**
     * Gets the attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @return the SOA_FLOWID
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @param value value to set the SOA_FLOWID
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Timestamp getStartDate() {
        return (Timestamp) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Timestamp value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for REQUEST_TYPE using the alias name RequestType.
     * @return the REQUEST_TYPE
     */
    public String getRequestType() {
        return (String) getAttributeInternal(REQUESTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_TYPE using the alias name RequestType.
     * @param value value to set the REQUEST_TYPE
     */
    public void setRequestType(String value) {
        setAttributeInternal(REQUESTTYPE, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxfndAttachment_EOView1.
     */
    public RowIterator getXxfndAttachment_EOView1() {
        return (RowIterator) getAttributeInternal(XXFNDATTACHMENT_EOVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XxfndLookupValues_V_ROVO1.
     */
    public RowSet getXxfndLookupValues_V_ROVO1() {
        return (RowSet) getAttributeInternal(XXFNDLOOKUPVALUES_V_ROVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXFND_TERRITORIES_ROVO1.
     */
    public RowSet getXXFND_TERRITORIES_ROVO1() {
        return (RowSet) getAttributeInternal(XXFND_TERRITORIES_ROVO1);
    }
}

