package model.am.common;

import java.math.BigDecimal;

import java.sql.Connection;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 09 11:37:05 IST 2020
// ---------------------------------------------------------------------
public interface Oando_AM extends ApplicationModule {
    Connection getCurrentConnection();

    String updateNewApprovedDependent(String hmo_ref_no);

    void filterUser();

    BigDecimal getPersonId(String userName);
}

