package model.vo;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 07 16:32:53 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxfndAttachment_EOViewDefImpl extends ViewDefImpl {
    public XxfndAttachment_EOViewDefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public XxfndAttachment_EOViewDefImpl() {
    }
}

